"""add_loadout_fields

Revision ID: b04d34368fe4
Revises: 0001
Create Date: 2026-02-22 12:04:21.421257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b04d34368fe4'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'status',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'lobby'::character varying"))
    op.alter_column('games', 'phase_number',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('users', sa.Column('active_shield', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('active_docs', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('active_bullet', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('active_role', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'active_role')
    op.drop_column('users', 'active_bullet')
    op.drop_column('users', 'active_docs')
    op.drop_column('users', 'active_shield')
    op.alter_column('games', 'phase_number',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('games', 'status',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'lobby'::character varying"))
    # ### end Alembic commands ###
