"""add_warn_count_to_user

Revision ID: c18b758a84f4
Revises: c331849fd1e3
Create Date: 2026-02-24 00:47:43.829119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c18b758a84f4'
down_revision: Union[str, None] = 'c331849fd1e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('warn_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'warn_count')
    # ### end Alembic commands ###
