"""add_lobby_persistence

Revision ID: c331849fd1e3
Revises: b04d34368fe4
Create Date: 2026-02-22 22:06:32.026048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c331849fd1e3'
down_revision: Union[str, None] = 'b04d34368fe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('lobby_message_id', sa.BigInteger(), nullable=True))
    op.add_column('games', sa.Column('lobby_end_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'lobby_end_time')
    op.drop_column('games', 'lobby_message_id')
    # ### end Alembic commands ###
